spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/ojt?serverTimezone=Asia/Seoul
    username: rms
    password: rms210601!

  sql:
    init:
      mode: always

